name: Release

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.12
      uses: actions/setup-java@v1
      with:
        java-version: 1.12
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Deploy to Github Package Registry
      env:
        GITHUB_PACKAGE: ${{ secrets.PACKAGE_TOKEN }}
      run: |
        mvn deploy -Dserver.username=rhughes1 -Dserver.password=4dde3d3b99249ad788a5ef6597382e6b1a06218e